server:
  port: 8090

spring:
  application:
    name: employee-management-server
  datasource:
    url: jdbc:mysql://localhost:3306/employee-management-db?createDatabaseIfNotExist=true
    username: root
    password: Dulan1998
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret: 7cvr45B1c8UAuybovBasiSzOZa1ZOXqRC4J50jChahF3yZDjbY
  expiration: 36000000

logging:
  level:
    org:
      springframework: DEBUG
